/*
 * Copyright 2022 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package models

import play.api.libs.json.{Format, Json, OFormat}
import uk.gov.hmrc.govukfrontend.views.viewmodels.select.SelectItem
import viewmodels.govuk.select._

final case class KindOfPackage(code: String, name: String)

object KindOfPackage {

  implicit val format: OFormat[KindOfPackage] =
    Json.format[KindOfPackage]

  val bulkKindsOfPackage: Seq[KindOfPackage] =
    Seq(
      KindOfPackage("VG", "Bulk, gas (at 1031 mbar and 15øC)"),
      KindOfPackage("VL", "Bulk, liquid"),
      KindOfPackage("VO", "Bulk, solid, large particles ('nodules')"),
      KindOfPackage("VQ", "Bulk, liquefied gas (at abnormal te"),
      KindOfPackage("VR", "Bulk, solid, granular particles"),
      KindOfPackage("VY", "Bulk, solid, fine particles ('powders')")
    )

  val unpackedKindsOfPackage: Seq[KindOfPackage] =
    Seq(
      KindOfPackage("NE", "Unpacked or unpackaged"),
      KindOfPackage("NF", "Unpacked or unpackaged, single unit"),
      KindOfPackage("NG", "Unpacked or unpackaged, multiple un"),
    )

  val standardKindsOfPackages: Seq[KindOfPackage] =
    Seq(
      KindOfPackage("1A", "Drum, steel"),
      KindOfPackage("1B", "Drum, aluminium"),
      KindOfPackage("1D", "Drum, plywood"),
      KindOfPackage("1G", "Drum, fibre"),
      KindOfPackage("1W", "Drum, wooden"),
      KindOfPackage("2C", "Barrel, wooden"),
      KindOfPackage("3A", "Jerrycan, steel"),
      KindOfPackage("3H", "Jerrycan, plastic"),
      KindOfPackage("43", "Bag, super bulk"),
      KindOfPackage("4A", "Box, steel"),
      KindOfPackage("4B", "Box, aluminium"),
      KindOfPackage("4C", "Box, natural wood"),
      KindOfPackage("4D", "Box, plywood"),
      KindOfPackage("4F", "Box, reconstituted wood"),
      KindOfPackage("4G", "Box, fibreboard"),
      KindOfPackage("4H", "Box, plastic"),
      KindOfPackage("5H", "Bag, woven plastic"),
      KindOfPackage("5L", "Bag, textile"),
      KindOfPackage("5M", "Bag, paper"),
      KindOfPackage("6H", "Composite packaging, plastic recept"),
      KindOfPackage("6P", "Composite packaging, glass receptac"),
      KindOfPackage("AA", "Intermediate bulk container, rigid"),
      KindOfPackage("AB", "Receptacle, fibre"),
      KindOfPackage("AC", "Receptacle, paper"),
      KindOfPackage("AD", "Receptacle, wooden"),
      KindOfPackage("AE", "Aerosol"),
      KindOfPackage("AF", "Pallet, modular, collars 80cms * 60"),
      KindOfPackage("AG", "Pallet, shrinkwrapped"),
      KindOfPackage("AH", "Pallet, 100cms * 110cms"),
      KindOfPackage("AI", "Clamshell"),
      KindOfPackage("AJ", "Cone"),
      KindOfPackage("AM", "Ampoule, non-protected"),
      KindOfPackage("AP", "Ampoule, protected"),
      KindOfPackage("AT", "Atomizer"),
      KindOfPackage("AV", "Capsule"),
      KindOfPackage("BA", "Barrel"),
      KindOfPackage("BB", "Bobbin"),
      KindOfPackage("BC", "Bottlecrate / bottlerack"),
      KindOfPackage("BD", "Board"),
      KindOfPackage("BE", "Bundle"),
      KindOfPackage("BF", "Balloon, non-protected"),
      KindOfPackage("BG", "Bag"),
      KindOfPackage("BH", "Bunch"),
      KindOfPackage("BI", "Bin"),
      KindOfPackage("BJ", "Bucket"),
      KindOfPackage("BK", "Basket"),
      KindOfPackage("BL", "Bale, compressed"),
      KindOfPackage("BM", "Basin"),
      KindOfPackage("BN", "Bale, non-compressed"),
      KindOfPackage("BO", "Bottle, non-protected, cylindrical"),
      KindOfPackage("BP", "Balloon, protected"),
      KindOfPackage("BQ", "Bottle, protected cylindrical"),
      KindOfPackage("BR", "Bar"),
      KindOfPackage("BS", "Bottle, non-protected, bulbous"),
      KindOfPackage("BT", "Bolt"),
      KindOfPackage("BU", "Butt"),
      KindOfPackage("BV", "Bottle, protected bulbous"),
      KindOfPackage("BW", "Box, for liquids"),
      KindOfPackage("BX", "Box"),
      KindOfPackage("BY", "Board, in bundle/bunch/truss"),
      KindOfPackage("BZ", "Bars, in bundle/bunch/truss"),
      KindOfPackage("CA", "Can, rectangular"),
      KindOfPackage("CB", "Crate, beer"),
      KindOfPackage("CC", "Churn"),
      KindOfPackage("CD", "Can, with handle and spout"),
      KindOfPackage("CE", "Creel"),
      KindOfPackage("CF", "Coffer"),
      KindOfPackage("CG", "Cage"),
      KindOfPackage("CH", "Chest"),
      KindOfPackage("CI", "Canister"),
      KindOfPackage("CJ", "Coffin"),
      KindOfPackage("CK", "Cask"),
      KindOfPackage("CL", "Coil"),
      KindOfPackage("CM", "Card"),
      KindOfPackage("CN", "Container, not otherwise specified"),
      KindOfPackage("CO", "Carboy, non-protected"),
      KindOfPackage("CP", "Carboy, protected"),
      KindOfPackage("CQ", "Cartridge"),
      KindOfPackage("CR", "Crate"),
      KindOfPackage("CS", "Case"),
      KindOfPackage("CT", "Carton"),
      KindOfPackage("CU", "Cup"),
      KindOfPackage("CV", "Cover"),
      KindOfPackage("CW", "Cage, roll"),
      KindOfPackage("CX", "Can, cylindrical"),
      KindOfPackage("CY", "Cylinder"),
      KindOfPackage("CZ", "Canvas"),
      KindOfPackage("DA", "Crate, multiple layer, plastic"),
      KindOfPackage("DB", "Crate, multiple layer, wooden"),
      KindOfPackage("DC", "Crate, multiple layer, cardboard"),
      KindOfPackage("DG", "Cage, Commonwealth Handling Equipme"),
      KindOfPackage("DH", "Box, Commonwealth Handling Equipmen"),
      KindOfPackage("DI", "Drum, iron"),
      KindOfPackage("DJ", "Demijohn, non-protected"),
      KindOfPackage("DK", "Crate, bulk, cardboard"),
      KindOfPackage("DL", "Crate, bulk, plastic"),
      KindOfPackage("DM", "Crate, bulk, wooden"),
      KindOfPackage("DN", "Dispenser"),
      KindOfPackage("DP", "Demijohn, protected"),
      KindOfPackage("DR", "Drum"),
      KindOfPackage("DS", "Tray, one layer no cover, plastic"),
      KindOfPackage("DT", "Tray, one layer no cover, wooden"),
      KindOfPackage("DU", "Tray, one layer no cover, polystyre"),
      KindOfPackage("DV", "Tray, one layer no cover, cardboard"),
      KindOfPackage("DW", "Tray, two layers no cover, plastic"),
      KindOfPackage("DX", "Tray, two layers no cover, wooden"),
      KindOfPackage("DY", "Tray, two layers no cover, cardboar"),
      KindOfPackage("EC", "Bag, plastic"),
      KindOfPackage("ED", "Case, with pallet base"),
      KindOfPackage("EE", "Case, with pallet base, wooden"),
      KindOfPackage("EF", "Case, with pallet base, cardboard"),
      KindOfPackage("EG", "Case, with pallet base, plastic"),
      KindOfPackage("EH", "Case, with pallet base, metal"),
      KindOfPackage("EI", "Case, isothermic"),
      KindOfPackage("EN", "Envelope"),
      KindOfPackage("FC", "Crate, fruit"),
      KindOfPackage("FD", "Crate, framed"),
      KindOfPackage("FI", "Firkin"),
      KindOfPackage("FL", "Flask"),
      KindOfPackage("FO", "Footlocker"),
      KindOfPackage("FP", "Filmpack"),
      KindOfPackage("FR", "Frame"),
      KindOfPackage("FT", "Foodtainer"),
      KindOfPackage("FX", "Bag, flexible container"),
      KindOfPackage("GB", "Bottle, gas"),
      KindOfPackage("GI", "Girder"),
      KindOfPackage("GR", "Receptacle, glass"),
      KindOfPackage("GZ", "Girders, in bundle/bunch/truss"),
      KindOfPackage("HA", "Basket, with handle, plastic"),
      KindOfPackage("HB", "Basket, with handle, wooden"),
      KindOfPackage("HC", "Basket, with handle, cardboard"),
      KindOfPackage("HG", "Hogshead"),
      KindOfPackage("HR", "Hamper"),
      KindOfPackage("IA", "Package, display, wooden"),
      KindOfPackage("IB", "Package, display, cardboard"),
      KindOfPackage("IC", "Package, display, plastic"),
      KindOfPackage("ID", "Package, display, metal"),
      KindOfPackage("IE", "Package, show"),
      KindOfPackage("IF", "Package, flow"),
      KindOfPackage("IG", "Package, paper wrapped"),
      KindOfPackage("IH", "Drum, plastic"),
      KindOfPackage("IK", "Package, cardboard, with bottle gri"),
      KindOfPackage("IN", "Ingot"),
      KindOfPackage("IZ", "Ingots, in bundle/bunch/truss"),
      KindOfPackage("JC", "Jerrycan, rectangular"),
      KindOfPackage("JG", "Jug"),
      KindOfPackage("JR", "Jar"),
      KindOfPackage("JT", "Jutebag"),
      KindOfPackage("JY", "Jerrycan, cylindrical"),
      KindOfPackage("KG", "Keg"),
      KindOfPackage("LG", "Log"),
      KindOfPackage("LT", "Lot"),
      KindOfPackage("LV", "Liftvan"),
      KindOfPackage("LZ", "Logs, in bundle/bunch/truss"),
      KindOfPackage("MB", "Bag, multiply"),
      KindOfPackage("MC", "Crate, milk"),
      KindOfPackage("MR", "Receptacle, metal"),
      KindOfPackage("MS", "Sack, multi-wall"),
      KindOfPackage("MT", "Mat"),
      KindOfPackage("MW", "Receptacle, plastic wrapped"),
      KindOfPackage("MX", "Matchbox"),
      KindOfPackage("NA", "Not available"),
      KindOfPackage("NS", "Nest"),
      KindOfPackage("NT", "Net"),
      KindOfPackage("NU", "Net, tube, plastic"),
      KindOfPackage("NV", "Net, tube, textile"),
      KindOfPackage("PA", "Packet"),
      KindOfPackage("PB", "Pallet, box"),
      KindOfPackage("PC", "Parcel"),
      KindOfPackage("PD", "Pallet, modular, collars 80cms * 10"),
      KindOfPackage("PE", "Pallet, modular, collars 80cms * 12"),
      KindOfPackage("PF", "Pen"),
      KindOfPackage("PG", "Plate"),
      KindOfPackage("PH", "Pitcher"),
      KindOfPackage("PI", "Pipe"),
      KindOfPackage("PJ", "Punnet"),
      KindOfPackage("PK", "Package"),
      KindOfPackage("PL", "Pail"),
      KindOfPackage("PN", "Plank"),
      KindOfPackage("PO", "Pouch"),
      KindOfPackage("PR", "Receptacle, plastic"),
      KindOfPackage("PT", "Pot"),
      KindOfPackage("PU", "Tray"),
      KindOfPackage("PV", "Pipes, in bundle/bunch/truss"),
      KindOfPackage("PX", "Pallet"),
      KindOfPackage("PY", "Plates, in bundle/bunch/truss"),
      KindOfPackage("PZ", "Planks, in bundle/bunch/truss"),
      KindOfPackage("QA", "Drum, steel, non-removable head"),
      KindOfPackage("QB", "Drum, steel, removable head"),
      KindOfPackage("QC", "Drum, aluminium, non-removable head"),
      KindOfPackage("QD", "Drum, aluminium, removable head"),
      KindOfPackage("QF", "Drum, plastic, non-removable head"),
      KindOfPackage("QG", "Drum, plastic, removable head"),
      KindOfPackage("QH", "Barrel, wooden, bung type"),
      KindOfPackage("QJ", "Barrel, wooden, removable head"),
      KindOfPackage("QK", "Jerrycan, steel, non-removable head"),
      KindOfPackage("QL", "Jerrycan, steel, removable head"),
      KindOfPackage("QM", "Jerrycan, plastic, non-removable he"),
      KindOfPackage("QN", "Jerrycan, plastic, removable head"),
      KindOfPackage("QP", "Box, wooden, natural wood, ordinary"),
      KindOfPackage("QQ", "Box, wooden, natural wood, with sif"),
      KindOfPackage("QR", "Box, plastic, expanded"),
      KindOfPackage("QS", "Box, plastic, solid"),
      KindOfPackage("RD", "Rod"),
      KindOfPackage("RG", "Ring"),
      KindOfPackage("RJ", "Rack, clothing hanger"),
      KindOfPackage("RK", "Rack"),
      KindOfPackage("RL", "Reel"),
      KindOfPackage("RO", "Roll"),
      KindOfPackage("RT", "Rednet"),
      KindOfPackage("RZ", "Rods, in bundle/bunch/truss"),
      KindOfPackage("SA", "Sack"),
      KindOfPackage("SB", "Slab"),
      KindOfPackage("SC", "Crate, shallow"),
      KindOfPackage("SD", "Spindle"),
      KindOfPackage("SE", "Sea-chest"),
      KindOfPackage("SH", "Sachet"),
      KindOfPackage("SI", "Skid"),
      KindOfPackage("SK", "Case, skeleton"),
      KindOfPackage("SL", "Slipsheet"),
      KindOfPackage("SM", "Sheetmetal"),
      KindOfPackage("SO", "Spool"),
      KindOfPackage("SP", "Sheet, plastic wrapping"),
      KindOfPackage("SS", "Case, steel"),
      KindOfPackage("ST", "Sheet"),
      KindOfPackage("SU", "Suitcase"),
      KindOfPackage("SV", "Envelope, steel"),
      KindOfPackage("SW", "Shrinkwrapped"),
      KindOfPackage("SX", "Set"),
      KindOfPackage("SY", "Sleeve"),
      KindOfPackage("SZ", "Sheets, in bundle/bunch/truss"),
      KindOfPackage("TB", "Tub"),
      KindOfPackage("TC", "Tea-chest"),
      KindOfPackage("TD", "Tube, collapsible"),
      KindOfPackage("TI", "Tierce"),
      KindOfPackage("TK", "Tank, rectangular"),
      KindOfPackage("TL", "Tub, with lid"),
      KindOfPackage("TN", "Tin"),
      KindOfPackage("TO", "Tun"),
      KindOfPackage("TR", "Trunk"),
      KindOfPackage("TS", "Truss"),
      KindOfPackage("TU", "Tube"),
      KindOfPackage("TV", "Tube, with nozzle"),
      KindOfPackage("TY", "Tank, cylindrical"),
      KindOfPackage("TZ", "Tubes, in bundle/bunch/truss"),
      KindOfPackage("UC", "Uncaged"),
      KindOfPackage("VA", "Vat"),
      KindOfPackage("VI", "Vial"),
      KindOfPackage("VK", "Vanpack"),
      KindOfPackage("VP", "Vacuum-packed"),
      KindOfPackage("WA", "Intermediate bulk container"),
      KindOfPackage("WB", "Wickerbottle"),
      KindOfPackage("WC", "Intermediate bulk container, steel"),
      KindOfPackage("WD", "Intermediate bulk container, alumin"),
      KindOfPackage("WF", "Intermediate bulk container, metal"),
      KindOfPackage("WG", "Intermediate bulk container, steel,"),
      KindOfPackage("WH", "Intermediate bulk container, alumin"),
      KindOfPackage("WJ", "Intermediate bulk container, metal,"),
      KindOfPackage("WK", "Intermediate bulk container, steel,"),
      KindOfPackage("WL", "Intermediate bulk container, alumin"),
      KindOfPackage("WM", "Intermediate bulk container, metal,"),
      KindOfPackage("WN", "Intermediate bulk container, woven"),
      KindOfPackage("WP", "Intermediate bulk container, woven"),
      KindOfPackage("WQ", "Intermediate bulk container, woven"),
      KindOfPackage("WR", "Intermediate bulk container, woven"),
      KindOfPackage("WS", "Intermediate bulk container, plasti"),
      KindOfPackage("WT", "Intermediate bulk container, textil"),
      KindOfPackage("WU", "Intermediate bulk container, natura"),
      KindOfPackage("WV", "Intermediate bulk container, textil"),
      KindOfPackage("WW", "Intermediate bulk container, textil"),
      KindOfPackage("WX", "Intermediate bulk container, textil"),
      KindOfPackage("WY", "Intermediate bulk container, plywoo"),
      KindOfPackage("WZ", "Intermediate bulk container, recons"),
      KindOfPackage("XA", "Bag, woven plastic, without inner c"),
      KindOfPackage("XB", "Bag, woven plastic, sift proof"),
      KindOfPackage("XC", "Bag, woven plastic, water resistant"),
      KindOfPackage("XD", "Bag, plastics film"),
      KindOfPackage("XF", "Bag, textile, without inner coat/li"),
      KindOfPackage("XG", "Bag, textile, sift proof"),
      KindOfPackage("XH", "Bag, textile, water resistant"),
      KindOfPackage("XJ", "Bag, paper, multi-wall"),
      KindOfPackage("XK", "Bag, paper, multi-wall, water resis"),
      KindOfPackage("YA", "Composite packaging, plastic recept"),
      KindOfPackage("YB", "Composite packaging, plastic recept"),
      KindOfPackage("YC", "Composite packaging, plastic recept"),
      KindOfPackage("YD", "Composite packaging, plastic recept"),
      KindOfPackage("YF", "Composite packaging, plastic recept"),
      KindOfPackage("YH", "Composite packaging, plastic recept"),
      KindOfPackage("YJ", "Composite packaging, plastic recept"),
      KindOfPackage("YK", "Composite packaging, plastic recept"),
      KindOfPackage("YL", "Composite packaging, plastic recept"),
      KindOfPackage("YM", "Composite packaging, plastic recept"),
      KindOfPackage("YN", "Composite packaging, glass receptac"),
      KindOfPackage("YP", "Composite packaging, glass receptac"),
      KindOfPackage("YQ", "Composite packaging, glass receptac"),
      KindOfPackage("YR", "Composite packaging, glass receptac"),
      KindOfPackage("YS", "Composite packaging, glass receptac"),
      KindOfPackage("YT", "Composite packaging, glass receptac"),
      KindOfPackage("YV", "Composite packaging, glass receptac"),
      KindOfPackage("YW", "Composite packaging, glass receptac"),
      KindOfPackage("YX", "Composite packaging, glass receptac"),
      KindOfPackage("YY", "Composite packaging, glass receptac"),
      KindOfPackage("YZ", "Composite packaging, glass receptac"),
      KindOfPackage("ZA", "Intermediate bulk container, paper,"),
      KindOfPackage("ZB", "Bag, large"),
      KindOfPackage("ZC", "Intermediate bulk container, paper,"),
      KindOfPackage("ZD", "Intermediate bulk container, rigid"),
      KindOfPackage("ZF", "Intermediate bulk container, rigid"),
      KindOfPackage("ZG", "Intermediate bulk container, rigid"),
      KindOfPackage("ZH", "Intermediate bulk container, rigid"),
      KindOfPackage("ZJ", "Intermediate bulk container, rigid"),
      KindOfPackage("ZK", "Intermediate bulk container, rigid"),
      KindOfPackage("ZL", "Intermediate bulk container, compos"),
      KindOfPackage("ZM", "Intermediate bulk container, compos"),
      KindOfPackage("ZN", "Intermediate bulk container, compos"),
      KindOfPackage("ZP", "Intermediate bulk container, compos"),
      KindOfPackage("ZQ", "Intermediate bulk container, compos"),
      KindOfPackage("ZR", "Intermediate bulk container, compos"),
      KindOfPackage("ZS", "Intermediate bulk container, compos"),
      KindOfPackage("ZT", "Intermediate bulk container, fibreb"),
      KindOfPackage("ZU", "Intermediate bulk container, flexib"),
      KindOfPackage("ZV", "Intermediate bulk container, metal,"),
      KindOfPackage("ZW", "Intermediate bulk container, natura"),
      KindOfPackage("ZX", "Intermediate bulk container, plywoo"),
      KindOfPackage("ZY", "Intermediate bulk container, recons"),
      KindOfPackage("ZZ", "Mutually defined")
    )

  val allKindsOfPackage: Seq[KindOfPackage] =
    (bulkKindsOfPackage ++ unpackedKindsOfPackage ++ standardKindsOfPackages).sortBy(_.code)

  def selectItems(kindsOfPackage: Seq[KindOfPackage]): Seq[SelectItem] =
    SelectItem(value = None, text = "Select a kind of package") +:
      kindsOfPackage.map {
        kindOfPackage =>
          SelectItemViewModel(
            value = kindOfPackage.code,
            text  = kindOfPackage.name
          )
      }
}
